fix(tsconfig): enforce `verbatimModuleSyntax` and fix files
BootNodeDev/dAppBooster pull request #310
Opened 2024-09-18 09:17 UTC by fernandomg

# Description:

By enabling `verbatimModuleSyntax` we will be forced to specify when we're importing a `type`.

# Steps:

`tsc` should pass without errors (that is, the build pass)

## Type of change:

- [x] New feature
- [ ] Bug fix
- [ ] Breaking change
- [ ] Enhancement
- [ ] Refactoring
- [x] Chore

# How Has This Been Tested?

- [x] Manual testing
- [ ] Automated tests
- [ ] Other (explain)

# Remember to check that:

- Your code follows the style guidelines of this project
- You have performed a self-review of your code
- You have commented your code in hard-to-understand areas
- You have made corresponding changes to the documentation
- Your changes generate no new warnings

# Screenshots

(Add screenshots or videos to help test this pull request)

2024-09-18 14:56 UTC, fernandomg commented
@nicosampler please re-check this, as it's completely different from what you approved

2024-09-19 14:22 UTC, gabitoesmiapodo commented on githooks/pre-push
> +#!/bin/sh
Just to keep consistency, this should be into `.husky/pre-push`

2024-09-19 14:27 UTC, gabitoesmiapodo requested changes
Close, but no cigar.

2024-09-19 19:35 UTC, gabitoesmiapodo approved these changes
Made a few extra changes to streamline the workflow a bit, but I think we're all set.

2024-09-19 20:12 UTC, merged